//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThoughtWorks.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThoughtWorks.VisualStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card could not be found:.
        /// </summary>
        internal static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string CardRank {
            get {
                return ResourceManager.GetString("CardRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cards satisfied the search criteria..
        /// </summary>
        internal static string CardSetIsEmpty {
            get {
                return ResourceManager.GetString("CardSetIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards (%%project%%).
        /// </summary>
        internal static string CardSetWindowTitle {
            get {
                return ResourceManager.GetString("CardSetWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string CardVersion {
            get {
                return ResourceManager.GetString("CardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card {0} - {1}.
        /// </summary>
        internal static string CardWindowCaption {
            get {
                return ResourceManager.GetString("CardWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your settings.
        /// </summary>
        internal static string CheckYourSettings {
            get {
                return ResourceManager.GetString("CheckYourSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to make this transition.
        /// </summary>
        internal static string ClickToMakeTransition {
            get {
                return ResourceManager.GetString("ClickToMakeTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We had problems retrieving your Mingle or GO password. Please enter them again..
        /// </summary>
        internal static string ErrorConvertingSecureStringToStringx {
            get {
                return ResourceManager.GetString("ErrorConvertingSecureStringToStringx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingle Explorer.
        /// </summary>
        internal static string ExplorerViewCaption {
            get {
                return ResourceManager.GetString("ExplorerViewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window is closing and may include data that has not been submitted. Do you wish to proceed? Click No to return to the form..
        /// </summary>
        internal static string FeedbackDataUnsubmittedWarning {
            get {
                return ResourceManager.GetString("FeedbackDataUnsubmittedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first fifty characters becomes the subject of this item in email..
        /// </summary>
        internal static string FeedbackDescriptionToolTip {
            get {
                return ResourceManager.GetString("FeedbackDescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback: Visual Studio Connector.
        /// </summary>
        internal static string FeedbackEmailSubject {
            get {
                return ResourceManager.GetString("FeedbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string FeedbackFormCompanyLabel {
            get {
                return ResourceManager.GetString("FeedbackFormCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FeedbackFormDescriptionLabel {
            get {
                return ResourceManager.GetString("FeedbackFormDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string FeedbackFormEmailLabel {
            get {
                return ResourceManager.GetString("FeedbackFormEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThoughtWorks Visual Studio Connector Feedback.
        /// </summary>
        internal static string FeedbackFormTitle {
            get {
                return ResourceManager.GetString("FeedbackFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string FeedbackFormTitleLabel {
            get {
                return ResourceManager.GetString("FeedbackFormTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        internal static string FeedbackTypeDefect {
            get {
                return ResourceManager.GetString("FeedbackTypeDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Resuest.
        /// </summary>
        internal static string FeedbackTypeFeature {
            get {
                return ResourceManager.GetString("FeedbackTypeFeature", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap grid {
            get {
                object obj = ResourceManager.GetObject("grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_action {
            get {
                object obj = ResourceManager.GetObject("icon_action", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add {
            get {
                object obj = ResourceManager.GetObject("icon_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_child {
            get {
                object obj = ResourceManager.GetObject("icon_add_child", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_in_next_line {
            get {
                object obj = ResourceManager.GetObject("icon_add_in_next_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_medium {
            get {
                object obj = ResourceManager.GetObject("icon_add_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_tag {
            get {
                object obj = ResourceManager.GetObject("icon_add_tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_tag_group {
            get {
                object obj = ResourceManager.GetObject("icon_add_tag_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_transition {
            get {
                object obj = ResourceManager.GetObject("icon_add_transition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_tree {
            get {
                object obj = ResourceManager.GetObject("icon_add_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_user {
            get {
                object obj = ResourceManager.GetObject("icon_add_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_variable {
            get {
                object obj = ResourceManager.GetObject("icon_add_variable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_workflow_transition {
            get {
                object obj = ResourceManager.GetObject("icon_add_workflow_transition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_all_items {
            get {
                object obj = ResourceManager.GetObject("icon_all_items", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_back {
            get {
                object obj = ResourceManager.GetObject("icon_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_cancel {
            get {
                object obj = ResourceManager.GetObject("icon_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_card_copy_to {
            get {
                object obj = ResourceManager.GetObject("icon_card_copy_to", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_delete {
            get {
                object obj = ResourceManager.GetObject("icon_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_delete_transition {
            get {
                object obj = ResourceManager.GetObject("icon_delete_transition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_disable_auto_enroll {
            get {
                object obj = ResourceManager.GetObject("icon_disable_auto_enroll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_edit {
            get {
                object obj = ResourceManager.GetObject("icon_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_edit_password {
            get {
                object obj = ResourceManager.GetObject("icon_edit_password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_edit_transition {
            get {
                object obj = ResourceManager.GetObject("icon_edit_transition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_edit_user {
            get {
                object obj = ResourceManager.GetObject("icon_edit_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_email {
            get {
                object obj = ResourceManager.GetObject("icon_email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_email_conf_test {
            get {
                object obj = ResourceManager.GetObject("icon_email_conf_test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_email_disabled {
            get {
                object obj = ResourceManager.GetObject("icon_email_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_enable_auto_enroll {
            get {
                object obj = ResourceManager.GetObject("icon_enable_auto_enroll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_export {
            get {
                object obj = ResourceManager.GetObject("icon_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_export1 {
            get {
                object obj = ResourceManager.GetObject("icon_export1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_forward {
            get {
                object obj = ResourceManager.GetObject("icon_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_grid_off {
            get {
                object obj = ResourceManager.GetObject("icon_grid_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_grid_on {
            get {
                object obj = ResourceManager.GetObject("icon_grid_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_help_new_window {
            get {
                object obj = ResourceManager.GetObject("icon_help_new_window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_help_unselected {
            get {
                object obj = ResourceManager.GetObject("icon_help_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_hide {
            get {
                object obj = ResourceManager.GetObject("icon_hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_hide_hidden {
            get {
                object obj = ResourceManager.GetObject("icon_hide_hidden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_hierarchy_disabled {
            get {
                object obj = ResourceManager.GetObject("icon_hierarchy_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_hierarchy_off {
            get {
                object obj = ResourceManager.GetObject("icon_hierarchy_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_hierarchy_on {
            get {
                object obj = ResourceManager.GetObject("icon_hierarchy_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_import {
            get {
                object obj = ResourceManager.GetObject("icon_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_import1 {
            get {
                object obj = ResourceManager.GetObject("icon_import1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_list_off {
            get {
                object obj = ResourceManager.GetObject("icon_list_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_list_off1 {
            get {
                object obj = ResourceManager.GetObject("icon_list_off1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_list_on {
            get {
                object obj = ResourceManager.GetObject("icon_list_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_lock {
            get {
                object obj = ResourceManager.GetObject("icon_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_manage_users {
            get {
                object obj = ResourceManager.GetObject("icon_manage_users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_preview {
            get {
                object obj = ResourceManager.GetObject("icon_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_print {
            get {
                object obj = ResourceManager.GetObject("icon_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_print_single_card {
            get {
                object obj = ResourceManager.GetObject("icon_print_single_card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_project_import {
            get {
                object obj = ResourceManager.GetObject("icon_project_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_quick_add_unselected {
            get {
                object obj = ResourceManager.GetObject("icon_quick_add_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_refresh {
            get {
                object obj = ResourceManager.GetObject("icon_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_refresh_hightlight {
            get {
                object obj = ResourceManager.GetObject("icon_refresh_hightlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_reset_tab {
            get {
                object obj = ResourceManager.GetObject("icon_reset_tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_revision_action {
            get {
                object obj = ResourceManager.GetObject("icon_revision_action", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_safe {
            get {
                object obj = ResourceManager.GetObject("icon_safe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_save {
            get {
                object obj = ResourceManager.GetObject("icon_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_show_hidden {
            get {
                object obj = ResourceManager.GetObject("icon_show_hidden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_show_latest {
            get {
                object obj = ResourceManager.GetObject("icon_show_latest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_source {
            get {
                object obj = ResourceManager.GetObject("icon_source", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_tab_checkbox_unselected {
            get {
                object obj = ResourceManager.GetObject("icon_tab_checkbox_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_temp {
            get {
                object obj = ResourceManager.GetObject("icon_temp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_template {
            get {
                object obj = ResourceManager.GetObject("icon_template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_transition {
            get {
                object obj = ResourceManager.GetObject("icon_transition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_tree_disabled {
            get {
                object obj = ResourceManager.GetObject("icon_tree_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_tree_off {
            get {
                object obj = ResourceManager.GetObject("icon_tree_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_tree_on {
            get {
                object obj = ResourceManager.GetObject("icon_tree_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_unlock {
            get {
                object obj = ResourceManager.GetObject("icon_unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_up {
            get {
                object obj = ResourceManager.GetObject("icon_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_update {
            get {
                object obj = ResourceManager.GetObject("icon_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_wiki_checkbox_unselected {
            get {
                object obj = ResourceManager.GetObject("icon_wiki_checkbox_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        internal static string ItemNotSet {
            get {
                return ResourceManager.GetString("ItemNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Name&quot; field may not be blank or empty..
        /// </summary>
        internal static string MingleCardNameNullOrEmpty {
            get {
                return ResourceManager.GetString("MingleCardNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingle Extention for Visual Studio.
        /// </summary>
        internal static string MingleExtensionTitle {
            get {
                return ResourceManager.GetString("MingleExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Favorites..
        /// </summary>
        internal static string MingleFavoritesLoadingError {
            get {
                return ResourceManager.GetString("MingleFavoritesLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingle or Go do not appear to be running. Try browsing to Mingle from a browser, then try this query again. This may also be caused by an errorneous URL for the Host or invalid credentials..
        /// </summary>
        internal static string MingleNotRunning {
            get {
                return ResourceManager.GetString("MingleNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murmurs.
        /// </summary>
        internal static string MurmurWindowTitle {
            get {
                return ResourceManager.GetString("MurmurWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New card.
        /// </summary>
        internal static string NewCardDefaultName {
            get {
                return ResourceManager.GetString("NewCardDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There do not seem to be any projects on this Mingle server..
        /// </summary>
        internal static string NoProjectsFound {
            get {
                return ResourceManager.GetString("NoProjectsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package property is null..
        /// </summary>
        internal static string PackageIsNull {
            get {
                return ResourceManager.GetString("PackageIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends Visual Studio to allow context-relevant connection to Mingle and GO..
        /// </summary>
        internal static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG-VSIX.
        /// </summary>
        internal static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property or field could not be updated..
        /// </summary>
        internal static string PropertyCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("PropertyCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the property is out of range, null or empty. A valid value is required..
        /// </summary>
        internal static string PropertyOutOfRange {
            get {
                return ResourceManager.GetString("PropertyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        internal static string PropertyValueNotSet {
            get {
                return ResourceManager.GetString("PropertyValueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select card....
        /// </summary>
        internal static string PropertyValueSelectCard {
            get {
                return ResourceManager.GetString("PropertyValueSelectCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made settings changes that have not been saved. Would you like to save them, now?.
        /// </summary>
        internal static string SettingsDataIsDirty {
            get {
                return ResourceManager.GetString("SettingsDataIsDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object disposed..
        /// </summary>
        internal static string SettingsViewControl_Dispose_Object_disposed_ {
            get {
                return ResourceManager.GetString("SettingsViewControl_Dispose_Object_disposed_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap spinner {
            get {
                object obj = ResourceManager.GetObject("spinner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitLabel {
            get {
                return ResourceManager.GetString("SubmitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a comment in the box below and close this form..
        /// </summary>
        internal static string TransitionAdmonitionLabel {
            get {
                return ResourceManager.GetString("TransitionAdmonitionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transition could not be applied..
        /// </summary>
        internal static string TransitionCannotBeApplied {
            get {
                return ResourceManager.GetString("TransitionCannotBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a comment for this transition. Do you wish to supply a comment?.
        /// </summary>
        internal static string TransitionCommentRequired {
            get {
                return ResourceManager.GetString("TransitionCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition = .
        /// </summary>
        internal static string TransitionEquals {
            get {
                return ResourceManager.GetString("TransitionEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a transition..
        /// </summary>
        internal static string TransitionIsNull {
            get {
                return ResourceManager.GetString("TransitionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Comment.
        /// </summary>
        internal static string TransitionWindowTitle {
            get {
                return ResourceManager.GetString("TransitionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url property is null or empty..
        /// </summary>
        internal static string UrlPropertyIsNullOrEmpty {
            get {
                return ResourceManager.GetString("UrlPropertyIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CardViewWindowPane constructor was called before first setting CardViewWindowPane.Model to a valid ViewModel reference..
        /// </summary>
        internal static string ViewModelInvalidOnCardViewWindowPaneConstructor {
            get {
                return ResourceManager.GetString("ViewModelInvalidOnCardViewWindowPaneConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view is not available in Visual Studio most likely because it is a personal favorite. Only team favorites may be queried through the Mingle API from a client like this..
        /// </summary>
        internal static string ViewNotUsableFromVisualStudio {
            get {
                return ResourceManager.GetString("ViewNotUsableFromVisualStudio", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap wiki_checkbox_selected {
            get {
                object obj = ResourceManager.GetObject("wiki_checkbox_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wiki_checkbox_unselected {
            get {
                object obj = ResourceManager.GetObject("wiki_checkbox_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
