//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThoughtWorks.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThoughtWorks.VisualStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @.
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build notifications from Go has yet to be implemented..
        /// </summary>
        internal static string BuildNotification {
            get {
                return ResourceManager.GetString("BuildNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be null or empty.
        /// </summary>
        internal static string CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to see that you are not using HTTPS on an HTTP connection or vise versa..
        /// </summary>
        internal static string CannotInterpretResponse {
            get {
                return ResourceManager.GetString("CannotInterpretResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string CardCreatedByLogin {
            get {
                return ResourceManager.GetString("CardCreatedByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string CardCreatedByName {
            get {
                return ResourceManager.GetString("CardCreatedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        internal static string CardCreatedOn {
            get {
                return ResourceManager.GetString("CardCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CardDescription {
            get {
                return ResourceManager.GetString("CardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string CardId {
            get {
                return ResourceManager.GetString("CardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        internal static string CardModifiedBy {
            get {
                return ResourceManager.GetString("CardModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        internal static string CardModifiedByLogin {
            get {
                return ResourceManager.GetString("CardModifiedByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        internal static string CardModifiedByName {
            get {
                return ResourceManager.GetString("CardModifiedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        internal static string CardModifiedOn {
            get {
                return ResourceManager.GetString("CardModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card could not be found:.
        /// </summary>
        internal static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id.
        /// </summary>
        internal static string CardProjectId {
            get {
                return ResourceManager.GetString("CardProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string CardProjectName {
            get {
                return ResourceManager.GetString("CardProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string CardRank {
            get {
                return ResourceManager.GetString("CardRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Cards Command Callback..
        /// </summary>
        internal static string CardsAllCommandCallback {
            get {
                return ResourceManager.GetString("CardsAllCommandCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cards satisfied the search criteria..
        /// </summary>
        internal static string CardSetIsEmpty {
            get {
                return ResourceManager.GetString("CardSetIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards (%%project%%).
        /// </summary>
        internal static string CardSetWindowTitle {
            get {
                return ResourceManager.GetString("CardSetWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Stories (%%project%%).
        /// </summary>
        internal static string CardSetWindowTitleStories {
            get {
                return ResourceManager.GetString("CardSetWindowTitleStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards for This User Command Callback..
        /// </summary>
        internal static string CardsThisUserCommandCallback {
            get {
                return ResourceManager.GetString("CardsThisUserCommandCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string CardVersion {
            get {
                return ResourceManager.GetString("CardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card {0} - {1}.
        /// </summary>
        internal static string CardWindowCaption {
            get {
                return ResourceManager.GetString("CardWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your settings.
        /// </summary>
        internal static string CheckYourSettings {
            get {
                return ResourceManager.GetString("CheckYourSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the field to edit its value.
        /// </summary>
        internal static string ClickToEdit {
            get {
                return ResourceManager.GetString("ClickToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to make this transition.
        /// </summary>
        internal static string ClickToMakeTransition {
            get {
                return ResourceManager.GetString("ClickToMakeTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We had problems retrieving your Mingle or GO password. Please enter them again..
        /// </summary>
        internal static string ErrorConvertingSecureStringToString {
            get {
                return ResourceManager.GetString("ErrorConvertingSecureStringToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Command Callback..
        /// </summary>
        internal static string ExplorerCommandCallback {
            get {
                return ResourceManager.GetString("ExplorerCommandCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingle Explorer.
        /// </summary>
        internal static string ExplorerViewCaption {
            get {
                return ResourceManager.GetString("ExplorerViewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window is closing and may include data that has not been submitted. Do you wish to proceed? Click No to return to the form..
        /// </summary>
        internal static string FeedbackDataUnsubmittedWarning {
            get {
                return ResourceManager.GetString("FeedbackDataUnsubmittedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first fifty characters becomes the subject of this item in email..
        /// </summary>
        internal static string FeedbackDescriptionToolTip {
            get {
                return ResourceManager.GetString("FeedbackDescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback: Visual Studio Connector.
        /// </summary>
        internal static string FeedbackEmailSubject {
            get {
                return ResourceManager.GetString("FeedbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string FeedbackFormCompanyLabel {
            get {
                return ResourceManager.GetString("FeedbackFormCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FeedbackFormDescriptionLabel {
            get {
                return ResourceManager.GetString("FeedbackFormDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string FeedbackFormEmailLabel {
            get {
                return ResourceManager.GetString("FeedbackFormEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThoughtWorks Visual Studio Connector Feedback.
        /// </summary>
        internal static string FeedbackFormTitle {
            get {
                return ResourceManager.GetString("FeedbackFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string FeedbackFormTitleLabel {
            get {
                return ResourceManager.GetString("FeedbackFormTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        internal static string FeedbackTypeDefect {
            get {
                return ResourceManager.GetString("FeedbackTypeDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Resuest.
        /// </summary>
        internal static string FeedbackTypeFeature {
            get {
                return ResourceManager.GetString("FeedbackTypeFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Results.
        /// </summary>
        internal static string GoPipelinePropertiesCaption {
            get {
                return ResourceManager.GetString("GoPipelinePropertiesCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap grid {
            get {
                object obj = ResourceManager.GetObject("grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name cannot be empty.\n.
        /// </summary>
        internal static string HostnameIsEmpty {
            get {
                return ResourceManager.GetString("HostnameIsEmpty", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap icon_action {
            get {
                object obj = ResourceManager.GetObject("icon_action", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_child {
            get {
                object obj = ResourceManager.GetObject("icon_add_child", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_in_next_line {
            get {
                object obj = ResourceManager.GetObject("icon_add_in_next_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_add_medium {
            get {
                object obj = ResourceManager.GetObject("icon_add_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_email_disabled {
            get {
                object obj = ResourceManager.GetObject("icon_email_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_grid_off {
            get {
                object obj = ResourceManager.GetObject("icon_grid_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_help_unselected {
            get {
                object obj = ResourceManager.GetObject("icon_help_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_hierarchy_disabled {
            get {
                object obj = ResourceManager.GetObject("icon_hierarchy_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_hierarchy_off {
            get {
                object obj = ResourceManager.GetObject("icon_hierarchy_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_list_off {
            get {
                object obj = ResourceManager.GetObject("icon_list_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_list_off1 {
            get {
                object obj = ResourceManager.GetObject("icon_list_off1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_quick_add_unselected {
            get {
                object obj = ResourceManager.GetObject("icon_quick_add_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_tab_checkbox_unselected {
            get {
                object obj = ResourceManager.GetObject("icon_tab_checkbox_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_tree_disabled {
            get {
                object obj = ResourceManager.GetObject("icon_tree_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_tree_off {
            get {
                object obj = ResourceManager.GetObject("icon_tree_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_wiki_checkbox_unselected {
            get {
                object obj = ResourceManager.GetObject("icon_wiki_checkbox_unselected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host name is malformed. The protocol must be either HTTP or HTTPS.\n.
        /// </summary>
        internal static string InvalidProtocol {
            get {
                return ResourceManager.GetString("InvalidProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a reference to IVsOutputWindow.
        /// </summary>
        internal static string IvsOutputWindowAccessFail {
            get {
                return ResourceManager.GetString("IvsOutputWindowAccessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name is malformed and must be like https://domain[:port] or http://domain[:port]\n.
        /// </summary>
        internal static string MalformedHostnameVarious {
            get {
                return ResourceManager.GetString("MalformedHostnameVarious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murmur Accepted.
        /// </summary>
        internal static string MessageMurmurCommitted {
            get {
                return ResourceManager.GetString("MessageMurmurCommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v2.
        /// </summary>
        internal static string MingleApiSegment {
            get {
                return ResourceManager.GetString("MingleApiSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Name&quot; field may not be blank or empty..
        /// </summary>
        internal static string MingleCardNameNullOrEmpty {
            get {
                return ResourceManager.GetString("MingleCardNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cards/&amp;&amp;card-no&amp;&amp;.
        /// </summary>
        internal static string MingleCardSegment {
            get {
                return ResourceManager.GetString("MingleCardSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cards.xml.
        /// </summary>
        internal static string MingleCardSetSegment {
            get {
                return ResourceManager.GetString("MingleCardSetSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Card Types..
        /// </summary>
        internal static string MingleCardTypesLoadingError {
            get {
                return ResourceManager.GetString("MingleCardTypesLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update attempt for this card has failed. The response received from the Mingle server is: [httpstatus].
        /// </summary>
        internal static string MingleCardUpdateError {
            get {
                return ResourceManager.GetString("MingleCardUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Favorites..
        /// </summary>
        internal static string MingleFavoritesLoadingError {
            get {
                return ResourceManager.GetString("MingleFavoritesLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingle or Go do not appear to be running. Try browsing to Mingle from a browser, then try this query again. This may also be caused by an errorneous URL for the Host or invalid credentials..
        /// </summary>
        internal static string MingleNotRunning {
            get {
                return ResourceManager.GetString("MingleNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /projects.
        /// </summary>
        internal static string MingleProjectsSegment {
            get {
                return ResourceManager.GetString("MingleProjectsSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Properties..
        /// </summary>
        internal static string MinglePropertiesLoadingError {
            get {
                return ResourceManager.GetString("MinglePropertiesLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Team members..
        /// </summary>
        internal static string MingleTeamMembersLoadingError {
            get {
                return ResourceManager.GetString("MingleTeamMembersLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cards/&amp;&amp;card-no&amp;&amp;/transitions.xml.
        /// </summary>
        internal static string MingleTransitionSetSegment {
            get {
                return ResourceManager.GetString("MingleTransitionSetSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading Mingle Transitions..
        /// </summary>
        internal static string MingleTransitionsLoadingError {
            get {
                return ResourceManager.GetString("MingleTransitionsLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the user, password, host or project settings required for Mingle interaction appear to be missing or invalid. Would you like to edit them now?.
        /// </summary>
        internal static string MissingOrInvalidCredentialData {
            get {
                return ResourceManager.GetString("MissingOrInvalidCredentialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A setting is missing or invalid..
        /// </summary>
        internal static string MissingOrInvalidSetting {
            get {
                return ResourceManager.GetString("MissingOrInvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murmurs.
        /// </summary>
        internal static string MurmurWindowTitle {
            get {
                return ResourceManager.GetString("MurmurWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New card.
        /// </summary>
        internal static string NewCardDefaultName {
            get {
                return ResourceManager.GetString("NewCardDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem connecting to the Mingle or Go. Some of the ThoughtWorks Exploer tree may not have been loaded. Please check your settings for a misspelled project name or similar issue..
        /// </summary>
        internal static string OtherConnectionError {
            get {
                return ResourceManager.GetString("OtherConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a reference to the Output window General pane.
        /// </summary>
        internal static string OutputWindowAccessFail {
            get {
                return ResourceManager.GetString("OutputWindowAccessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write on the Output window.
        /// </summary>
        internal static string OutputWindowWriteFail {
            get {
                return ResourceManager.GetString("OutputWindowWriteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package property is null..
        /// </summary>
        internal static string PackageIsNull {
            get {
                return ResourceManager.GetString("PackageIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem querying pipeline properties..
        /// </summary>
        internal static string PipelineSearchError {
            get {
                return ResourceManager.GetString("PipelineSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select (click on) a row in the list..
        /// </summary>
        internal static string PleaseSelectRowFirst {
            get {
                return ResourceManager.GetString("PleaseSelectRowFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends Visual Studio to allow context-relevant connection to Mingle and GO..
        /// </summary>
        internal static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG-VSIX.
        /// </summary>
        internal static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property or field could not be updated..
        /// </summary>
        internal static string PropertyCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("PropertyCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the property is out of range, null or empty. A valid value is required..
        /// </summary>
        internal static string PropertyOutOfRange {
            get {
                return ResourceManager.GetString("PropertyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Current Iteration).
        /// </summary>
        internal static string PropertyValueCurrentIteration {
            get {
                return ResourceManager.GetString("PropertyValueCurrentIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        internal static string PropertyValueNotSet {
            get {
                return ResourceManager.GetString("PropertyValueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select card....
        /// </summary>
        internal static string PropertyValueSelectCard {
            get {
                return ResourceManager.GetString("PropertyValueSelectCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made settings changes that have not been saved. Would you like to save them, now?.
        /// </summary>
        internal static string SettingsDataIsDirty {
            get {
                return ResourceManager.GetString("SettingsDataIsDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object disposed..
        /// </summary>
        internal static string SettingsViewControl_Dispose_Object_disposed_ {
            get {
                return ResourceManager.GetString("SettingsViewControl_Dispose_Object_disposed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitLabel {
            get {
                return ResourceManager.GetString("SubmitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be serializable..
        /// </summary>
        internal static string TheTypeMustBeSerializable {
            get {
                return ResourceManager.GetString("TheTypeMustBeSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a comment in the box below and close this form..
        /// </summary>
        internal static string TransitionAdmonitionLabel {
            get {
                return ResourceManager.GetString("TransitionAdmonitionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transition could not be applied..
        /// </summary>
        internal static string TransitionCannotBeApplied {
            get {
                return ResourceManager.GetString("TransitionCannotBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a comment for this transition. Do you wish to supply a comment?.
        /// </summary>
        internal static string TransitionCommentRequired {
            get {
                return ResourceManager.GetString("TransitionCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition = .
        /// </summary>
        internal static string TransitionEquals {
            get {
                return ResourceManager.GetString("TransitionEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a transition..
        /// </summary>
        internal static string TransitionIsNull {
            get {
                return ResourceManager.GetString("TransitionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Comment.
        /// </summary>
        internal static string TransitionWindowTitle {
            get {
                return ResourceManager.GetString("TransitionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mingle/Go Settings Command Callback..
        /// </summary>
        internal static string TwSettingsCommandCallback {
            get {
                return ResourceManager.GetString("TwSettingsCommandCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url property is null or empty..
        /// </summary>
        internal static string UrlPropertyIsNullOrEmpty {
            get {
                return ResourceManager.GetString("UrlPropertyIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CardViewWindowPane constructor was called before first setting CardViewWindowPane.Model to a valid ViewModel reference..
        /// </summary>
        internal static string ViewModelInvalidOnCardViewWindowPaneConstructor {
            get {
                return ResourceManager.GetString("ViewModelInvalidOnCardViewWindowPaneConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view is not available in Visual Studio most likely because it is a personal favorite. Only team favorites may be queried through the Mingle API from a client like this..
        /// </summary>
        internal static string ViewNotUsableFromVisualStudio {
            get {
                return ResourceManager.GetString("ViewNotUsableFromVisualStudio", resourceCulture);
            }
        }
    }
}
